# Week 11 Homework - Getting data


1. Load the dataframe saved from this week's lab.
1. Scrape data from this page https://en.wikipedia.org/wiki/List_of_countries_by_past_and_projected_GDP_(nominal)
1. Append to the dataframe: projected GDP (nominal) from IMF estimates from 2022 to 2027. (If data is not available for the country use None)
1. Add a new column and calculate average increase in terms of percentage. 
1. Sort by this column in descending order.

<h4>imports</h4>

In [20]:
import pandas as pd
import pandas as pd
from bs4 import BeautifulSoup
import requests
import re
import numpy as np

In [2]:
country_list_df = pd.read_csv('countrydata.csv')
country_list_df.drop('Unnamed: 0', axis=1, inplace=True)

In [3]:
response = requests.get('https://en.wikipedia.org/wiki/List_of_countries_by_past_and_projected_GDP_(nominal)')
response.ok

True

In [4]:
html_doc = response.text
soup = BeautifulSoup(html_doc, 'html.parser')

In [5]:
t = soup.find_all('table')[5]
t=t.find_all('tr')

In [24]:
data=[[y.text.lstrip('\xa0').rstrip().replace(',', '') for y in x.find_all('td')] for x in t]

In [26]:
df2=pd.DataFrame(data, columns=['CountryName', "Year 2020", "Year 2021", "Year 2022", "Year 2023", "Year 2024", "Year 2025", "Year 2026", "Year 2027"])

In [27]:
df2 = df2.iloc[1: , :]
df2.drop(df2.columns[[1, 2]], axis=1, inplace=True)
country_list_df=country_list_df.sort_values(by='CountryName')

In [28]:
combined_df=pd.merge(country_list_df, df2, left_on="CountryName", right_on="CountryName")

In [35]:
combined_df[["Year 2022", "Year 2023", "Year 2024", "Year 2025", "Year 2026", "Year 2027"]]=combined_df[["Year 2022", "Year 2023", "Year 2024", "Year 2025", "Year 2026", "Year 2027"]].apply(pd.to_numeric)

In [44]:
def annualGrowthRate(a, b, c, d, e, f):
    return ((((b-a)/a)*100)+(((c-b)/b)*100)+(((d-c)/c)*100)+(((e-d)/d)*100)+(((f-e)/e)*100))/5

In [45]:
combined_df['average_rate'] = combined_df.apply(lambda row : annualGrowthRate(row['Year 2022'],
                     row['Year 2023'], row['Year 2024'], row['Year 2025'], row['Year 2026'], row['Year 2027']), axis = 1)

In [47]:
combined_df.head(30)

,CountryName,Capital,Population,Area,Year 2022,Year 2023,Year 2024,Year 2025,Year 2026,Year 2027,average_rate
0,Afghanistan,Kabul,29121286,647500.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Albania,Tirana,2986952,28748.0,17942.0,19062.0,20339.0,21622.0,22931.0,24249.0,6.210261
2,Algeria,Algiers,34586184,2381740.0,193601.0,199382.0,204551.0,212973.0,222863.0,231837.0,3.673266
3,Andorra,Andorra la Vella,84000,468.0,3400.0,3580.0,3755.0,3913.0,4072.0,4225.0,4.442171
4,Angola,Luanda,13068161,1246700.0,124862.0,133335.0,140706.0,150343.0,159450.0,167503.0,6.054215
5,Antigua and Barbuda,St. John's,86754,443.0,1621.0,1768.0,1900.0,2016.0,2113.0,2214.0,6.446249
6,Argentina,Buenos Aires,41343201,2766890.0,564277.0,573633.0,573964.0,587988.0,616405.0,646202.0,2.765206
7,Armenia,Yerevan,2968000,29800.0,14047.0,15842.0,17258.0,18377.0,19726.0,21251.0,8.654471
8,Aruba,Oranjestad,71566,193.0,3229.0,3395.0,3529.0,3632.0,3732.0,3834.0,3.498598
9,Australia,Canberra,21515754,7686850.0,1748334.0,1828394.0,1917797.0,2000036.0,2089911.0,2185847.0,4.568245
10,Austria,Vienna,8205000,83858.0,479815.0,518808.0,550551.0,578061.0,605395.0,630527.0,5.624368
11,Azerbaijan,Baku,8303512,86600.0,73369.0,72912.0,73439.0,74776.0,77001.0,80080.0,1.778934
12,Bahamas,Nassau,301790,13940.0,12627.0,13630.0,14425.0,15074.0,15660.0,16257.0,5.194980
13,Bahrain,Manama,738004,665.0,44169.0,45421.0,47067.0,48958.0,51068.0,53407.0,3.873221
14,Bangladesh,Dhaka,156118464,144000.0,396543.0,438436.0,481002.0,526838.0,576122.0,628412.0,9.646662
15,Barbados,Bridgetown,285653,431.0,5530.0,5926.0,6234.0,6522.0,6806.0,7083.0,5.080527
16,Belarus,Minsk,9685000,207600.0,59394.0,60188.0,62866.0,64824.0,66496.0,68362.0,2.857253
17,Belgium,Brussels,10403000,30510.0,609887.0,639716.0,667661.0,694257.0,720983.0,746317.0,4.121221
18,Belize,Belmopan,314522,22966.0,1991.0,2135.0,2226.0,2316.0,2409.0,2507.0,4.724318
19,Benin,Porto-Novo,9056010,112620.0,18387.0,20029.0,21842.0,23869.0,26032.0,28306.0,9.011950
20,Bhutan,Thimphu,699847,47000.0,2653.0,2881.0,3179.0,3474.0,3775.0,4089.0,9.039913
21,Bolivia,Sucre,9947418,1098580.0,41032.0,43351.0,46482.0,49792.0,53287.0,57027.0,6.806592
22,Bosnia and Herzegovina,Sarajevo,4590000,51129.0,23358.0,24971.0,26672.0,28412.0,30158.0,32259.0,6.670617
23,Botswana,Gaborone,2029307,600370.0,18426.0,19821.0,21331.0,22866.0,24705.0,26525.0,7.558909
24,Brazil,Brasília,201103330,8511965.0,1833274.0,1980483.0,2124987.0,2228793.0,2328671.0,2447681.0,5.960632
25,Brunei,Bandar Seri Begawan,395027,5770.0,35555.0,27708.0,23049.0,21322.0,20624.0,20464.0,-10.085363
26,Bulgaria,Sofia,7148785,110910.0,89533.0,97798.0,104502.0,111547.0,117871.0,124403.0,6.807737
27,Burkina Faso,Ouagadougou,16241811,274200.0,19621.0,21280.0,23111.0,25060.0,27141.0,29152.0,8.241258
28,Burundi,Bujumbura,9863117,27830.0,3431.0,3686.0,3992.0,4322.0,4635.0,4947.0,7.594772
29,Cambodia,Phnom Penh,14453680,181040.0,28020.0,30239.0,32688.0,35412.0,38424.0,41803.0,8.330213